import type { DefaultLayoutTranslations } from 'vidstack';

export const BULGARIAN_PLAYER: DefaultLayoutTranslations = {
	'Caption Styles': 'Стилове на субтитрите',
	'Captions look like this': 'Субтитрите изглеждат така',
	'Closed-Captions Off': 'Изключени субтитри',
	'Closed-Captions On': 'Включени субтитри',
	'Display Background': 'Покажи фон',
	'Enter Fullscreen': 'Премини в цял екран',
	'Enter PiP': 'Премини в PiP',
	'Exit Fullscreen': 'Изход от цял екран',
	'Exit PiP': 'Изход от PiP',
	'Google Cast': 'Google Cast',
	'Keyboard Animations': 'Анимации на клавиатурата',
	'Seek Backward': 'Прескочи назад',
	'Seek Forward': 'Прескочи напред',
	'Skip To Live': 'Прескочи към НА ЖИВО',
	'Text Background': 'Фон на текста',
	Accessibility: 'Достъпност',
	AirPlay: 'AirPlay',
	Announcements: 'Известия',
	Audio: 'Звук',
	Auto: 'Автоматично',
	Boost: 'Увеличи',
	Captions: 'Субтитри',
	Chapters: 'Глави',
	Color: 'Цвят',
	Connected: 'Свързано',
	Connecting: 'Свързване',
	Continue: 'Продължи',
	Default: 'По подразбиране',
	Disabled: 'Неактивно',
	Disconnected: 'Отвързано',
	Download: 'Изтегли',
	Family: 'Семейство',
	Font: 'Шрифт',
	Fullscreen: 'Цял екран',
	LIVE: 'НА ЖИВО',
	Loop: 'Повтаряне',
	Mute: 'Заглуши',
	Normal: 'Нормално',
	Off: 'Изключено',
	Opacity: 'Прозрачност',
	Pause: 'Пауза',
	PiP: 'PiP',
	Play: 'Пусни',
	Playback: 'Възпроизвеждане',
	Quality: 'Качество',
	Replay: 'Пусни отначало',
	Reset: 'Ресет',
	Seek: 'Плъзгане',
	Settings: 'Настройки',
	Shadow: 'Сянка',
	Size: 'Размер',
	Speed: 'Скорост',
	Text: 'Текст',
	Track: '',
	Unmute: 'Отглоши',
	Volume: 'Звук'
};
